/**
 * @file st_compiler.h
 * @brief Structured Text (IEC 61131-3) compiler utilities for the IDE.
 */

#ifndef ST_COMPILER_H
#define ST_COMPILER_H

#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/** @brief Maximum size of generated C source artefact. */
#define STC_MAX_OUTPUT 16384U
/** @brief Maximum number of highlight tokens produced for syntax support. */
#define STC_MAX_TOKENS 512U

/**
 * @brief Highlight token for IDE front-end.
 */
typedef struct
{
    size_t start;   /**< Offset from start of file. */
    size_t length;  /**< Length in bytes. */
    char category[16]; /**< Token category (keyword, identifier, literal). */
} stc_highlight_token;

/**
 * @brief Output artefacts generated by the compiler.
 */
typedef struct
{
    char c_source[STC_MAX_OUTPUT]; /**< Generated C code. */
    size_t c_length;               /**< Length of generated C code. */
    stc_highlight_token tokens[STC_MAX_TOKENS]; /**< Highlight tokens. */
    size_t token_count;            /**< Number of valid highlight tokens. */
} stc_compilation;

/**
 * @brief Compile Structured Text file into C representation.
 * @param path Path to source file.
 * @param out Compilation artefacts.
 * @return True on success.
 */
bool stc_compile_file(const char *path, stc_compilation *out);

/**
 * @brief Compile Structured Text source string.
 * @param source Null-terminated source string.
 * @param out Compilation artefacts.
 * @return True on success.
 */
bool stc_compile_string(const char *source, stc_compilation *out);

#ifdef __cplusplus
}
#endif

#endif
