if(TARGET_OS STREQUAL "host")
    add_compile_definitions(OSAL_TARGET_POSIX=1)
elseif(TARGET_OS STREQUAL "qnx")
    add_compile_definitions(OSAL_TARGET_QNX=1)
elseif(TARGET_OS STREQUAL "vxworks")
    add_compile_definitions(OSAL_TARGET_VXWORKS=1)
elseif(TARGET_OS STREQUAL "baget")
    add_compile_definitions(OSAL_TARGET_BAGET=1)
elseif(TARGET_OS STREQUAL "qemu")
    add_compile_definitions(OSAL_TARGET_POSIX=1 OSAL_TARGET_QEMU=1)
else()
    message(FATAL_ERROR "Unsupported TARGET_OS=${TARGET_OS}")
endif()
